### ISSUE TITLE
cabal install scion-browser fails under Fedora 16

### ISSUE THREAD

**Issue by bokesan** [serras/scion-class-browser#7]
Because of a change in linker behavior, scion-browser fails to build under Fedora 16.

$ cabal install scion-browser
...
Linking dist/build/scion-browser/scion-browser ...
/usr/bin/ld: /home/breitko/.cabal/lib/terminfo-0.3.2.3/ghc-7.0.4/libHSterminfo-0.3.2.3.a(Base.o): undefined reference to symbol 'tparm'
/usr/bin/ld: note: 'tparm' is defined in DSO /lib64/libtinfo.so.5 so try adding it to the linker command line
/lib64/libtinfo.so.5: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
cabal: Error: some packages failed to install:

The cause is explained here: http://lists.fedoraproject.org/pipermail/devel/2010-March/133601.html

I got it to build by adding this to the executable section of scion-browser.cabal:

 Extra-libraries:
    tinfo  

However, I have no idea if this will break the build on other systems and if it is the "right" way to fix it.

**Comment by JPMoresmau** [comment]
Well, I think adding a library would break things, but I've added to workaround to the eclipsefp FAQ page (http://eclipsefp.github.com/faq.html)

**Comment by serras** [comment]
I've checked, and in my Ubuntu system it builds correctly with the "extra-libraries" added to the Cabal file.
@JPMoresmau May you try to build that way on Windows? I think if it builds fine in all these systems, we can release a new version which includes it.

**Comment by JPMoresmau** [comment]
Nope, doesn't build on Windows:
cabal.exe: Missing dependencies on foreign libraries:
- Missing C libraries: tinfo, tinfo
  This problem can usually be solved by installing the system packages that
  provide these libraries (you may need the "-dev" versions). If the libraries
  are already installed but in a non-standard location then you can use the
  flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.

Really, we don't want to impose the burden of having these types of libraries present on a Windows machine. Or add it with a flag so that's it's only added on Unix machines.

**Comment by serras** [comment]
In the new branch I've added the Extra-libraries: tinfo section to all architectures but Windows.
I don't know if there is another way to check for this library, because we may run into problems in Mac OS X...

**Comment by serras** [comment]
Finally, I decided not including `Extra-libraries: tinfo` by default, because I don't know whether it works in Mac OS X, and in Debian system it's not needed (it does not hurt, either, apart from having to install libtinfo-dev).
Thanks for the report, the comments and changing the things in the FAQ.

**Comment by johnpmayer** [comment]
Hey, we just saw this again over at faylang/fay. The guys who develop ln (the linker) changed some default behavior that allows some package management systems to replace symlinks with link scripts. Gcc understood how to do it properly, but ghc 7.0.4 didn't. It's fixed now in ghc 7.4.1.
